# -*- coding: utf-8 -*-
"""DeepWalk-SSP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15KqsakD2hf9kTlaGEgSs-bD4ElPnVyPl

# Deepwalk-SSP

Deepwalk-SSP is a Python repository that implements student representation learning using DeepWalk, a network representation learning technique.

## M. Amintoosi
"""

import scipy.io
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore", category=UserWarning)

def create_graph_from_bow(student_course_matrix):
    """
    Creates a NetworkX graph from a bag-of-words (BoW) representation.

    Args:
        student_course_matrix: A NumPy array representing the BoW representation. Each row corresponds to a node (e.g., student),
           and each column corresponds to a feature (e.g., course).  A non-zero value indicates the presence of the feature.

    Returns:
        A NetworkX graph where nodes represent samples from student_course_matrix, and edges represent common features with weights based on the number of common features.  Returns None if input is invalid.
    """
    if not isinstance(student_course_matrix, np.ndarray):
        print("Error: Input student_course_matrix must be a NumPy array.")
        return None
    if student_course_matrix.ndim != 2:
        print("Error: Input student_course_matrix must be a 2D NumPy array.")
        return None

    G = nx.Graph()

    num_nodes = student_course_matrix.shape[0]
    for i in range(num_nodes):
        G.add_node(i)

    for i in range(num_nodes):
        for j in range(i + 1, num_nodes):
            common_courses = np.sum(student_course_matrix[i] * student_course_matrix[j])
            if common_courses > 0:
                G.add_edge(i, j, weight=common_courses)
    return G

# Example Usage:
# Assuming 'student_course_matrix' is your NumPy array representing the BoW
#G = create_graph_from_bow(student_course_matrix)

#if G:
#    print(f"Graph created with {G.number_of_nodes()} nodes and {G.number_of_edges()} edges.")

import networkx as nx
from tqdm import tqdm

def generate_random_walks(G, num_walks_per_node=80, walk_length=10):
    """
    Generates random walks from a given graph.

    Args:
        G: A NetworkX graph.
        num_walks_per_node: The number of random walks to generate per node.
        walk_length: The length of each random walk.

    Returns:
        A list of random walks (each walk is a list of node IDs).  Returns an empty list if the input graph is invalid.

    """
    if not isinstance(G, nx.Graph):
        print("Error: Input must be a NetworkX graph.")
        return []

    walks = []
    def random_walk(start_node, walk_length):
        walk = [start_node]
        current_node = start_node
        for _ in range(walk_length -1):  # -1 because we already added the start node
            neighbors = list(G.neighbors(current_node))
            if neighbors:
                next_node = np.random.choice(neighbors)
                walk.append(next_node)
                current_node = next_node
            else: #Handle isolated nodes
                break #or append current node again, depending on your needs
        return walk

    import numpy as np
    for node in tqdm(G.nodes, desc="Nodes"):
        for _ in range(num_walks_per_node):
            walks.append(random_walk(node, walk_length))
    return walks

# Example usage (assuming 'G' is your NetworkX graph):
#walks = generate_random_walks(G)

#print(f"Generated {len(walks)} random walks.")

from gensim.models import Word2Vec
import numpy as np

def train_word2vec(walks, vector_size=5, window=5, hs=1, sg=1, workers=2, seed=1, epochs=30):
    """
    Trains a Word2Vec model on a list of random walks.

    Args:
        walks: A list of random walks (each walk is a list of node IDs).
        vector_size: Dimensionality of the word embeddings.
        window: Context window size.
        hs: If 1, hierarchical softmax will be used for model training.
        sg: If 1, skip-gram architecture will be used (otherwise CBOW is used).
        workers: Number of worker threads to use.
        seed: Seed for random number generator.
        epochs: Number of training epochs.

    Returns:
        A trained gensim Word2Vec model. Returns None if input is invalid or training fails.

    """
    if not isinstance(walks, list):
        print("Error: Walks must be a list.")
        return None
    if not all(isinstance(walk, list) for walk in walks):
        print("Error: Each walk must be a list.")
        return None
    if len(walks) == 0:
        print("Error: Walks list is empty.")
        return None

    try:
        wv_model = Word2Vec(walks, hs=hs, sg=sg, vector_size=vector_size, window=window, workers=workers, seed=seed)
        wv_model.train(walks, total_examples=wv_model.corpus_count, epochs=epochs, report_delay=1)
        return wv_model
    except Exception as e:
        print(f"An error occurred during Word2Vec training: {e}")
        return None


# Example Usage (assuming 'walks' is your list of random walks):
#wv_model = train_word2vec(walks)

#if wv_model:
#    print(f'Shape of embedding matrix: {wv_model.wv.vectors.shape}')
#    # Access node embeddings:  wv_model.wv['node_id']  (replace 'node_id' with an actual node ID)

import numpy as np
import os

def read_class(file_number):
    """Reads a class student data file and returns student_course_matrix and L (Students' labels).

    Args:
        file_number: The number of the file to read (integer).

    Returns:
        A tuple containing:
            - student_course_matrix: A NumPy array representing the BoW matrix from the file.
            - L: A list of student IDs from the file.
            - Returns (None, None) if the file is not found or an error occurs during processing.
    """
    fname = str(file_number)
    L = []
    try:
        with open(fname, 'r') as f:
            line1 = f.readline().strip().split()
            num_students = int(line1[0])
            num_courses = int(line1[1])

            student_course_matrix = np.zeros((num_students, num_courses), dtype=int)

            for j in range(num_students):
                line = f.readline().strip().split()
                student_id = line[1]
                L.append(student_id)
                course_vector_str = line[2]

                #Robust handling of course vectors:
                if len(course_vector_str) != num_courses:
                    print(f"Warning: Unexpected course vector length in file {fname}, line {j+2}. Using 0 padding.")
                    course_vector_str += "0" * (num_courses - len(course_vector_str))


                course_vector = np.array([int(c) for c in course_vector_str])
                student_course_matrix[j, :] = course_vector

        return student_course_matrix, L

    except FileNotFoundError:
        print(f"Error: File '{fname}' not found.")
        return None, None
    except Exception as e:
        print(f"An error occurred while processing file '{fname}': {e}")
        return None, None


# Example usage:  Read data from file number 3
# L_3, D_3 = read_class(3)

# if L_3 is not None:
#     print("Student IDs (L) from file 3:", L_3)
#     print("\nBag-of-Words matrix (student_course_matrix) from file 3:\n", D_3)

import numpy as np
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

def compute_balance_score(labels):
    # Count the occurrences of each cluster
    _ , counts = np.unique(labels, return_counts=True)

    # Calculate the average number of instances per cluster
    avg_count = np.mean(counts)

    # Balance score is defined as the average count divided by the maximum count
    max_count = np.max(counts)
    if avg_count == 0:
        return 0  # avoid division by zero

    # Balance score can be defined as a ratio of the most populated cluster to the average
    balance_score = avg_count / max_count

    return balance_score


def cluster_and_evaluate(student_course_matrix, n_clusters=2):
    """
    Performs KMeans clustering on a single representation of student data and evaluates
    clustering efficiency using the silhouette score and balance score.

    Args:
        student_course_matrix: NumPy array representing the representation.
        n_clusters: The number of clusters for KMeans (default is 2).

    Returns:
        A dictionary containing the silhouette score and balance score:
        {'silhouette_score': silhouette_avg, 'balance_score': balance_score}
        Returns None if input data is invalid or clustering fails.
    """
    if not isinstance(student_course_matrix, np.ndarray):
        print("Error: Input data must be a NumPy array.")
        return None
    if student_course_matrix.shape[0] < n_clusters:
        print("Error: Number of samples must be greater than or equal to the number of clusters")
        return None

    try:
        kmeans = KMeans(n_clusters=n_clusters, n_init='auto', random_state=0)
        kmeans.fit(student_course_matrix)
        labels = kmeans.labels_
        silhouette_avg = silhouette_score(student_course_matrix, labels)

        balance_score = compute_balance_score(labels)

        return {'silhouette_score': silhouette_avg, 'balance_score': balance_score, 'labels': labels}

    except Exception as e:
        print(f"An error occurred during clustering: {e}")
        return None

import pandas as pd


def process_and_cluster(filepath, num_walks_per_node=80, walk_length=10, vector_size=5, epochs=30, n_clusters=2):
    """
    Processes a single file, generates embeddings, performs clustering, and returns results.
    """
    try:
        student_course_matrix, _ = read_class(filepath)
        # print(student_course_matrix)
        G = create_graph_from_bow(student_course_matrix)
        if G:
            walks = generate_random_walks(G, num_walks_per_node, walk_length)
            wv_model = train_word2vec(walks, vector_size=vector_size, epochs=epochs)
            if wv_model:
                embeddings = wv_model.wv.vectors

                # Cluster and evaluate on student_course_matrix
                student_course_matrix_results = cluster_and_evaluate(student_course_matrix, n_clusters)

                # Cluster and evaluate on embeddings
                embeddings_results = cluster_and_evaluate(embeddings, n_clusters)

                return {
                    'G' : G,
                    'embeddings': embeddings,
                    'file_index': os.path.splitext(os.path.basename(filepath))[0],
                    'vector_size': vector_size,
                    'BoW.silhouette_score': student_course_matrix_results['silhouette_score'],
                    'BoW.balance_score': student_course_matrix_results['balance_score'],
                    'BoW.labels': student_course_matrix_results['labels'].tolist(),
                    'embeddings.silhouette_score': embeddings_results['silhouette_score'],
                    'embeddings.balance_score': embeddings_results['balance_score'],
                    'embeddings.labels': embeddings_results['labels'].tolist()
                }

    except Exception as e:
        print(f"Error processing {filepath}: {e}")

    return None

"""# Main script

If you wish to view the results discussed in the paper, please refrain from running the upcoming cell code and proceed directly to the next cell that loads our results.
"""

import networkx as nx
import matplotlib.pyplot as plt
import pickle
import pandas as pd

# Create an empty DataFrame to store the results
df = pd.DataFrame(columns=['file_index', 'vector_size', 'BoW.silhouette_score',
                          'BoW.balance_score', 'BoW.labels',
                          'embeddings.silhouette_score', 'embeddings.balance_score', 'embeddings.labels'])

# Process and cluster the files for different vector sizes
vector_sizes = [1, 2, 3, 5, 10]
all_graphs = {}

for i in range(1, 7):
    print("file number:", i)
    for vector_size in vector_sizes:
        filepath = f"data/{i}.txt"
        result = process_and_cluster(filepath, vector_size=vector_size)
        if result:
            df = pd.concat([df, pd.DataFrame([result])], ignore_index=True)
            all_graphs[(i, vector_size)] = result['G']

# Save the graphs to a pickle file
with open('results/graphs.pkl', 'wb') as f:
    pickle.dump({'all_graphs': all_graphs}, f)


# Print the DataFrame
# print(df)

# Save the DataFrame to an Excel file
df.to_excel('results/df.xlsx', index=False)  # Set index=True if you want to save the index

"""## Loading Pre-trained Results

In this section, we will load the results from a previous training phase to facilitate comparison and analysis. Given the stochastic nature of neural network training, the results may vary with each run.

We will load the results that have been saved, including performance metrics stored in a DataFrame and graph data serialized in a pickle file. Please ensure that the necessary files (`df.xlsx` and `graphs.pkl`) are located in the `results` directory for the following code to execute successfully.

Please note that if you executed the training cell above, your results will overwrite the previous results.
"""

# Load the results

import pickle
import pandas as pd
vector_sizes = [1, 2, 3, 5, 10]

df = pd.read_excel('results/df.xlsx')
# Load the graphs from the pickle file
with open('results/graphs.pkl', 'rb') as f:
    graph_data = pickle.load(f)

# Extract the graphs
all_graphs = graph_data['all_graphs']

import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
import ast
from collections import Counter

# Extract the graphs
all_graphs = graph_data['all_graphs'].copy()

file_number = 2
walk_lenght = 80
for i in [file_number]:
    for vector_size in [2]:
        print(i, vector_size)
        # BoW Labels graph
        G_bow = all_graphs[(i, vector_size)].copy()  # Create a deep copy of the graph
        walks = generate_random_walks(G_bow)

        print(f"Generated {len(walks)} random walks.")

        pos = nx.spring_layout(G_bow)

        # Decrease all edge weights by 1 for reducing the course
        for u, v, data in G_bow.edges(data=True):
            data['weight'] = max(0, data['weight'] - 1)  # Ensure weights don't go below 0

        # Draw the full graph with variable edge widths
        fig = plt.figure(figsize=(10, 8))
        nx.draw(G_bow, pos, with_labels=True, width=0.2, font_size=14, node_color='tab:blue')

        # Highlight the nodes on the selected random walk
        selected_node = 40
        walk_nodes = walks[selected_node*walk_lenght]
        print(walk_nodes)
        plt.title(f"A Random walk started from {walk_nodes[0]} and ended at {walk_nodes[-1]}: {walk_nodes}")

        walk_edges = [(walk_nodes[i], walk_nodes[i+1]) for i in range(len(walk_nodes)-1)]

        # Draw the nodes on the selected random walk
        nx.draw_networkx_nodes(G_bow, pos, nodelist=walk_nodes, node_color='tab:orange', node_size=300)

        # Draw the edges on the selected random walk
        nx.draw_networkx_edges(G_bow, pos, edgelist=walk_edges, edge_color='tab:orange', width=2)

        # # Save the figure
        fig.savefig(f"results/random-walk-{file_number}-node{selected_node}.png", dpi=100)  # Adjust dpi as needed
        # # plt.close()  # Close the plot if you are done with it

"""## Compare representation methods"""

vector_size = 2
filtered_df = df[df['vector_size'] == vector_size]

# Filter to keep only the first occurrence of each file_index
unique_filtered_df = filtered_df[['file_index', 'BoW.silhouette_score', 'embeddings.silhouette_score']].drop_duplicates(subset='file_index')

df_melted_silhouette = unique_filtered_df.melt(id_vars=['file_index'],
                                                 value_vars=['BoW.silhouette_score', 'embeddings.silhouette_score'],
                                                 var_name='Method',
                                                 value_name='Silhouette Score')

df_melted_silhouette.loc[df_melted_silhouette['Method'] == 'BoW.silhouette_score', 'Method'] = 'Student-Course Representation'
df_melted_silhouette.loc[df_melted_silhouette['Method'] == 'embeddings.silhouette_score', 'Method'] = 'DeepWalk Embeddings'

plt.figure(figsize=(10, 6))
sns.barplot(x='file_index', y='Silhouette Score', hue='Method', data=df_melted_silhouette)
plt.title('Silhouette Score Comparison (vector_size=2)')
plt.xlabel('File Index')
plt.ylabel('Silhouette Score')
plt.tight_layout()
plt.savefig(f"results/silhouette_score_comparison_vector-size-{vector_size}.png")
plt.show()

average_bow = df_melted_silhouette.groupby('Method')['Silhouette Score'].mean()['Student-Course Representation']
average_deepwalk = df_melted_silhouette.groupby('Method')['Silhouette Score'].mean()['DeepWalk Embeddings']
mean_diff = average_deepwalk - average_bow
print(mean_diff)

file_number = 5
filepath = f"data/{file_number}.txt"
result = process_and_cluster(filepath, vector_size=2)

student_course_matrix, _ = read_class(filepath)
student_course_matrix.shape

import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# Step 1: Apply PCA
pca = PCA(n_components=2)
reduced_matrix = pca.fit_transform(student_course_matrix)
labels = result['BoW.labels']
# Step 2: Visualize the result
plt.figure(figsize=(8, 6))
plt.scatter(reduced_matrix[:, 0], reduced_matrix[:, 1], c=labels, marker='o')

# plt.title('PCA of Student Course Matrix')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
# plt.grid()
plt.savefig(f"results/PCA-BoW-{file_number}.png")
plt.show()

# from matplotlib.colors import ListedColormap
data = result['embeddings']
labels = result['embeddings.labels']
x = data[:, 0]  # x-coordinates
y = data[:, 1]  # y-coordinates

# Define a colormap and create a list of unique labels
unique_labels = np.unique(labels)

# Create a scatter plot with colors based on labels
plt.figure(figsize=(8, 6))
scatter = plt.scatter(x, y, c=labels,  marker='o') #cmap=cmap,
# plt.title(f"Scatter Plot of {len(x)} Points")
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.xlim(min(x) - 0.1, max(x) + 0.1)
plt.ylim(min(y) - 0.1, max(y) + 0.1)
# plt.grid(True)
plt.savefig(f"results/DeepWalk-Two-Dim-Space-{file_number}.png")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

def plot_scores(df, score_name, file_indices=None):
    # Validate score_name
    if score_name not in ['silhouette', 'balance']:
        raise ValueError("score_name must be either 'silhouette' or 'balance'")

    # Filter the dataframe based on the file_indices if provided
    if file_indices is not None:
        df = df[df['file_index'].isin(file_indices)]

    # Determine the corresponding column names based on the score name
    if score_name == 'silhouette':
        column_name_bow = "BoW.silhouette_score"
        column_name_embeddings = "embeddings.silhouette_score"
        title = "Silhouette Scores for Different Vector Sizes"
    elif score_name == 'balance':
        column_name_bow = "BoW.balance_score"
        column_name_embeddings = "embeddings.balance_score"
        title = "Balance Scores for Different Vector Sizes"

    # Plot the scores
    fig = plt.figure(figsize=(6, 4))
    sns.lineplot(x="vector_size", y=column_name_bow, data=df,
                 label="Student-Course Representation", marker='o')
    sns.lineplot(x="vector_size", y=column_name_embeddings, data=df,
                 label="DeepWalk Embeddings", marker='s')
    plt.title(title)
    plt.xlabel("Vector Size")
    plt.ylabel(f"{score_name.capitalize()} Score")
    plt.legend()
    plt.show()

    # Create a descriptive filename
    if file_indices is not None:
        file_indices_str = "_".join(map(str, file_indices))
        score_png_file_name = f'results/{score_name}_score_file_indices_{file_indices_str}.png'
    else:
        score_png_file_name = f'results/{score_name}_score.png'

    fig.savefig(score_png_file_name)
    print(f"Figure saved as: {score_png_file_name}")

import pandas as pd

# Read the Excel file
# df = pd.read_excel('results/df.xlsx')
plot_scores(df, 'silhouette')
# Group the data by 'vector_size' and calculate the mean of the scores
average_scores = df.groupby('vector_size')[['BoW.silhouette_score', 'embeddings.silhouette_score']].mean()

# Print the average scores
print(average_scores)

plot_scores(df, 'silhouette', file_indices=[5])

"""Run various clustering methods"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering, MeanShift
from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score
from gensim.models import Word2Vec
import networkx as nx
import ast  # Needed to safely evaluate a string that represents a list

# load the previous computed embeddings
df = pd.read_excel('results/df.xlsx')

from sklearn.cluster import KMeans, AgglomerativeClustering, AffinityPropagation
from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score

def cluster_students_and_evaluate(data):
    results = {}

    # KMeans
    kmeans = KMeans(n_clusters=2, n_init=10, random_state=42).fit(data)
    results['kmeans_labels'] = kmeans.labels_
    results['kmeans_silhouette'] = silhouette_score(data, kmeans.labels_)
    results['kmeans_davies_bouldin'] = davies_bouldin_score(data, kmeans.labels_)
    results['kmeans_calinski_harabasz'] = calinski_harabasz_score(data, kmeans.labels_)

    # Affinity Propagation
    affinity = AffinityPropagation().fit(data)
    results['affinity_labels'] = affinity.labels_
    results['affinity_silhouette'] = silhouette_score(data, affinity.labels_)
    results['affinity_davies_bouldin'] = davies_bouldin_score(data, affinity.labels_)
    results['affinity_calinski_harabasz'] = calinski_harabasz_score(data, affinity.labels_)

    # Gaussian Mixture Model
    gmm = GaussianMixture(n_components=2, random_state=42).fit(data)
    gmm_labels = gmm.predict(data)
    results['gmm_labels'] = gmm_labels
    results['gmm_silhouette'] = silhouette_score(data, gmm_labels)
    results['gmm_davies_bouldin'] = davies_bouldin_score(data, gmm_labels)
    results['gmm_calinski_harabasz'] = calinski_harabasz_score(data, gmm_labels)

    # Agglomerative Clustering
    agglomerative = AgglomerativeClustering(n_clusters=2).fit(data)
    results['agglomerative_labels'] = agglomerative.labels_
    results['agglomerative_silhouette'] = silhouette_score(data, agglomerative.labels_)
    results['agglomerative_davies_bouldin'] = davies_bouldin_score(data, agglomerative.labels_)
    results['agglomerative_calinski_harabasz'] = calinski_harabasz_score(data, agglomerative.labels_)

    return results

# Main Processing

# Loop over file_index
for file_index in range(1, 7):  # Adjust based on actual file indices
    print(f"Processing file index: {file_index}")

    # Get the embeddings for vector_size=2 for the current file_index
    embeddings_row = df[(df['file_index'] == file_index) & (df['vector_size'] == 2)]
    if embeddings_row.empty:
        print(f"No embeddings found for file_index={file_index} and vector_size=2")
        continue

    # Extract the embeddings
    # Extract the embeddings (assuming it's a list of lists represented as a string)
    embeddings_str = embeddings_row['embeddings'].values[0]  # Get the string representation

    cleaned_str = embeddings_str.replace('\n', ', ').replace('[', '').replace(']', '')
    # Convert the cleaned string to a numpy array
    embeddings_list = np.array([[float(num) for num in row.split()] for row in cleaned_str.split(',') if row])

    # Convert the list of lists to a numpy array
    embeddings = np.array(embeddings_list)

    file_path = f"data/{file_index}.txt"  # Update the path based on your data files
    # print(type(embeddings[0]))
    # Process data and get student-course matrix
    student_course_matrix, courses = read_class(file_path)

    # Cluster and evaluate raw data and embeddings
    results_student_course = cluster_students_and_evaluate(student_course_matrix)
    results_embeddings = cluster_students_and_evaluate(embeddings)

    # Store results in a DataFrame
    df_results = pd.DataFrame([results_student_course, results_embeddings],
                                index=['Student-Course Representation', 'DeepWalk Embeddings'])

    # Save and visualize results
    # print(df_results)

    # # Visualizing silhouette scores
    # silhouette_metrics = df_results[['kmeans_silhouette', 'affinity_silhouette', \
    #                                  'gmm_silhouette', 'agglomerative_silhouette']]
    # silhouette_metrics.plot.bar()
    # plt.title(f'Silhouette Score Comparison for file_index={file_index}')
    # plt.ylabel('Silhouette Score')
    # plt.tight_layout()
    # # plt.savefig(f'results/silhouette_score_comparison_file_{file_index}.png')
    # plt.show()
    # break

import pandas as pd

df = pd.read_excel('results/df.xlsx')

df.columns

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score

# Main Processing

# Initialize a dictionary to store results for all file indices
all_results = {
    'Method': [],
    'File Index': [],
    'Silhouette Score': [],
    'Davies–Bouldin index' : [],
    'Calinski–Harabasz index' : []
}

# Loop over file_index
for file_index in range(1, 7):  # Adjust based on actual file indices
    print(f"Processing file index: {file_index}")

    # Get the embeddings for vector_size=2 for the current file_index
    embeddings_row = df[(df['file_index'] == file_index) & (df['vector_size'] == 2)]
    if embeddings_row.empty:
        print(f"No embeddings found for file_index={file_index} and vector_size=2")
        continue

    # Extract the embeddings
    embeddings_str = embeddings_row['embeddings'].values[0]  # Get the string representation
    cleaned_str = embeddings_str.replace('\n', ', ').replace('[', '').replace(']', '')
    embeddings_list = np.array([[float(num) for num in row.split()] for row in cleaned_str.split(',') if row])
    embeddings = np.array(embeddings_list)

    file_path = f"data/{file_index}.txt"  # Update the path based on your data files
    student_course_matrix, courses = read_class(file_path)

    # Cluster and evaluate raw data and embeddings
    results_student_course = cluster_students_and_evaluate(student_course_matrix)
    results_embeddings = cluster_students_and_evaluate(embeddings)


    # Store results for DeepWalk Embeddings
    for method in ['kmeans', 'affinity', 'gmm', 'agglomerative']:
        all_results['Method'].append(f'DeepWalk Embeddings {method}')
        all_results['File Index'].append(file_index)
        all_results['Silhouette Score'].append(results_embeddings[f'{method}_silhouette'])
        all_results['Davies–Bouldin index'].append(results_embeddings[f'{method}_davies_bouldin'])
        all_results['Calinski–Harabasz index'].append(results_embeddings[f'{method}_calinski_harabasz'])

    # Store results for Student-Course Representation
    for method in ['kmeans', 'affinity', 'gmm', 'agglomerative']:
        all_results['Method'].append(f'Student-Course Representation {method}')
        all_results['File Index'].append(file_index)
        all_results['Silhouette Score'].append(results_student_course[f'{method}_silhouette'])
        all_results['Davies–Bouldin index'].append(results_student_course[f'{method}_davies_bouldin'])
        all_results['Calinski–Harabasz index'].append(results_student_course[f'{method}_calinski_harabasz'])

# Convert results to DataFrame
df_all_results = pd.DataFrame(all_results)

# Visualizing silhouette scores for all file indices
plt.figure(figsize=(12, 6))
for method in df_all_results['Method'].unique():
    subset = df_all_results[df_all_results['Method'] == method]
    plt.plot(subset['File Index'], subset['Silhouette Score'], marker='o', label=method)

plt.title('Silhouette Score Comparison Across File Indices')
plt.xlabel('File Index')
plt.ylabel('Silhouette Score')
plt.xticks(range(1, 7))  # Adjust based on the number of files
plt.legend()
plt.tight_layout()
plt.savefig('results/silhouette_score_comparison_all_files.png')
plt.show()

# Visualizing Davies–Bouldin index for all file indices
# Lower value is better
plt.figure(figsize=(12, 6))
for method in df_all_results['Method'].unique():
    subset = df_all_results[df_all_results['Method'] == method]
    plt.plot(subset['File Index'], subset['Davies–Bouldin index'], marker='o', label=method)

plt.title('Davies–Bouldin index Comparison Across File Indices')
plt.xlabel('File Index')
plt.ylabel('Davies–Bouldin index')
plt.xticks(range(1, 7))  # Adjust based on the number of files
plt.legend()
plt.tight_layout()
plt.savefig('results/DBI_comparison_all_files.png')
plt.show()

# Visualizing Calinski–Harabasz index for all file indices
# Lower value is better
plt.figure(figsize=(12, 6))
for method in df_all_results['Method'].unique():
    subset = df_all_results[df_all_results['Method'] == method]
    plt.plot(subset['File Index'], subset['Calinski–Harabasz index'], marker='o', label=method)

plt.title('Calinski–Harabasz index Comparison Across File Indices')
plt.xlabel('File Index')
plt.ylabel('Calinski–Harabasz index')
plt.xticks(range(1, 7))  # Adjust based on the number of files
plt.legend()
plt.tight_layout()
plt.savefig('results/CHI_comparison_all_files.png')
plt.show()

# df_all_results